#!/usr/bin/with-contenv bash
# shellcheck shell=bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 12380" \
        s6-setuidgid abc /app/inpx-web --lib-dir=/library --app-dir=/data --inpx=/catalog.inpx
