name: Build Docker image

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - id: inpxweb
        uses: pozetroninc/github-action-get-latest-release@v0.8.0
        with:
          owner: bookpauk
          repo: inpx-web
          excludes: prerelease,draft

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          build-args: INPX_RELEASE=${{ steps.inpxweb.outputs.release }}
          tags: ghcr.io/dekan/inpx-web:latest, ghcr.io/dekan/inpx-web:${{ steps.inpxweb.outputs.release }}
